name: Generate File Name Prefix
description: Generates consistent artifact filename prefix across workflows

outputs:
  name:
    description: Generated artifact name
    value: ${{ steps.generate.outputs.name }}

runs:
  using: composite
  steps:
    - name: Generate artifact filename
      id: generate
      shell: bash
      run: |
        SHORT_SHA=$(echo "$GITHUB_SHA" | cut -c1-7)
        BRANCH=$(echo "$GITHUB_REF_NAME" | tr '/' '-')
        FILE="${GITHUB_RUN_NUMBER}-${SHORT_SHA}-${BRANCH}"
        echo "name=$FILE" >> $GITHUB_OUTPUT